---
title: "Lab_10: Distances and the Border Zone"
subtitle: 'Ecosystem Science and Sustainability 523c'
author:
  name: Louisa Jade Beckett
  email: beckettl@colostate.edu
format: html
---



```{r}
library(tidyverse)
library(sf)
library(units)

library(gghighlight)
library(ggrepel)
library(knitr)
```

##Question 1
```{r}
#1.1
eqdc <- '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'
```

```{r}
#1.2
remotes::install_github("ropensci/USAboundaries")
remotes::install_github("ropensci/USAboundariesData")
remotes::install_github("mikejohnson51/AOI")
remotes::install_github("ropenscilabs/rnaturalearthdata")
```

```{r}
#1.3
library(AOI)
library(sf)

eqdc <- st_crs(5070)
states <- USAboundaries::us_states(resolution = "low") %>% filter(!state_abbr %in% c("HI", "AK", "PR")) %>% st_transform(eqdc)

countries <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") |>
  st_transform(eqdc)
```

```{r}
#1.4
library(readr)

us_cities <- read_csv("data/simplemaps_uscities_basicv1.90/uscities.csv", show_col_types = FALSE) |>
  st_as_sf(coords = c("lng", "lat"), crs = 4326) |>
  st_transform(eqdc)
```

##Question 2
```{r}
#2.1
library(flextable)
library(units)
library(dplyr)

us <- st_union(states) %>% st_cast("MULTILINESTRING") %>%
  st_as_sf()

us_cities$dist_to_us_border <- st_distance(us_cities, us) %>% set_units("km") %>% drop_units()

farthest_cities <- us_cities %>% arrange(desc(dist_to_us_border)) %>% st_drop_geometry() %>% slice_max(dist_to_us_border, n = 5) %>% select(city, state_name, dist_to_us_border) %>% flextable::flextable()
farthest_cities
```

```{r}
#2.2
state_borders <- states %>% st_cast("MULTILINESTRING") %>%
  st_as_sf()

us_cities <- us_cities %>% st_filter(st_union(states)) %>% mutate(
  dist_to_st_border = st_distance(., state_borders) %>% apply(1, min) %>% set_units("km"))

select(us_cities, city, state_name, dist_to_st_border) %>% st_drop_geometry() %>% slice_max(dist_to_st_border, n = 5) %>%
  flextable::flextable()
```
```{r}
#2.3
#mexico
mx <- filter(countries, admin == "Mexico") %>% st_cast("MULTILINESTRING") %>% st_as_sf()

us_cities <- us_cities %>% st_filter(st_union(states)) %>%
  mutate(distance_to_mx_border = set_units(st_distance(., mx), "km"))

select(us_cities, city, state_name, distance_to_mx_border) %>%
  st_drop_geometry() %>%
  slice_max(distance_to_mx_border, n = 5) %>%
  flextable::flextable()
```
```{r}
#2.4
canada <- filter(countries, admin == "Canada") %>% st_cast("MULTILINESTRING") %>% st_as_sf()

us_cities <- us_cities %>% st_filter(st_union(states)) %>%
  mutate(distance_to_canada_border = set_units(st_distance(., canada), "km"))

select(us_cities, city, state_name, distance_to_canada_border) %>%
  st_drop_geometry() %>%
  slice_max(distance_to_canada_border, n = 5) %>%
  flextable::flextable()
```


##Question 3
```{r}
#3.1
library(ggplot2)

na <- filter(countries, admin %in% c("Mexico", "Canada", "United States of America")) |>
  st_as_sf()

big_cities <- us_cities |>
  slice_max(population, n = 10)

ggplot() +
  geom_sf(data = na, fill = "lightblue") +
  geom_sf(data = states, fill = "white", lty = 2, size = 0.5) +
  geom_sf(data = big_cities, color = 'purple', size = .5) +
  ggrepel::geom_label_repel(data = big_cities,
                            aes(geometry = geometry, label = city, label.size = .1),
                            stat = "sf_coordinates") +
  theme_void()
```

```{r}
#3.2 
five_farthest <- us_cities %>%
  slice_max(dist_to_us_border, n = 5)

ggplot() +
  geom_sf(data = st_union(states), fill = "grey", lty = 2, size = 0.5) +
  geom_sf(data = us_cities, aes(color = as.numeric(dist_to_us_border)), size = 0.5) +
  geom_sf(data = five_farthest, color = "red", size = 0.7) +
  ggrepel::geom_label_repel(data = five_farthest,
                            aes(geometry = geometry, label = city),
                            stat = "sf_coordinates") +
  scale_color_viridis_c() +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(color = "Distance to Border (km)")
```

```{r}
#3.3
five_farthest <- us_cities %>%
  slice_max(dist_to_st_border, n = 5)

ggplot() +
  geom_sf(data = st_union(states), fill = "grey", lty = 2, size = 0.5) +
  geom_sf(data = us_cities, aes(color = as.numeric(dist_to_st_border)), size = 0.5) +
  geom_sf(data = five_farthest, color = "red", size = 0.7) +
  ggrepel::geom_label_repel(data = five_farthest,
                            aes(geometry = geometry, label = city),
                            stat = "sf_coordinates") +
  scale_color_viridis_c() +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(color = "Distance to State Border (km)")

```

```{r}
#3.4
library(gghighlight)

us_cities <- us_cities %>%
  mutate(can_mx_dist = abs(as.numeric(distance_to_canada_border - distance_to_mx_border)))

five_farthest <- us_cities %>%
  filter(can_mx_dist < 100) %>%
  slice_max(population, n = 5)

ggplot() +
  geom_sf(data = st_union(states), fill = "grey", lty = 2, size = 0.5) +
  geom_sf(data = us_cities, aes(color = as.numeric(dist_to_us_border)), size = 0.5) +
  geom_sf(data = five_farthest, color = 'red', size = 0.7) +
  ggrepel::geom_label_repel(
    data = five_farthest,
    aes(geometry = geometry, label = city),
    stat = "sf_coordinates"
  ) +
  scale_color_viridis_c() +
  gghighlight(can_mx_dist < 100) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(color = "Distance to US Border (km)")
```

##Question 4
```{r}
#4.1
us_cities <- us_cities %>% mutate(within_160_km = dist_to_us_border <= 160)

cities_in_zone <- us_cities %>% filter(within_160_km) %>% nrow()

print(cities_in_zone)

#how many cities are in the 160 km border zone? - there are 12,939 cities within this border
```

```{r}
pop_in_zone <- us_cities %>% filter(within_160_km) %>% summarise(population = sum(population, na.rm = TRUE)) %>% pull(population)

print(pop_in_zone)

# how many people live in the city within 160 km of the border - There are 255,296,982 people who live within 160 km of the US border.
```

```{r}
total_population <- us_cities %>% summarise(population = sum(population, na.rm = TRUE)) %>% pull(population)

percentage <- (pop_in_zone / total_population) * 100

border_zone_summary <- tibble(
  `Cities in 100-Mile Zone` = cities_in_zone,
  `Population in 100-Mile Zone` = pop_in_zone,
  `Total Population` = total_population,
  `Percentage of Population in Zone` = round(percentage, 2)
)

flextable::flextable(border_zone_summary)

# what percentage of the total population is in this zone? - 64.44% of the total population live within this 160 km zone
```
#does it match the ACLUE estimate in the link above? - it falls just below the ACLU estimate of 66%.


```{r}
#4.2
top_10_cities <- us_cities %>%
  filter(within_160_km) %>%
  slice_max(population, n = 10)

ggplot() +
  geom_sf(data = st_union(states), fill = "grey85", color = "white") +
  geom_sf(data = us_cities, aes(color = as.numeric(within_160_km)), size = 0.5) +
  geom_sf(data = top_10_cities, color = "black", size = 1) +
  ggrepel::geom_label_repel(
    data = top_10_cities,
    aes(geometry = geometry, label = city),
    stat = "sf_coordinates",
    size = 3,
    color = "black",
    fill = "white"
  ) +
  scale_color_gradient(low = "orange", high = "darkred", guide = "none") +
  gghighlight(within_160_km) +
  theme_void() +
  labs(title = "Cities within 160-km border zone",
       subtitle = "Top 10 Most Populated Cities")
```

```{r}
#4.3
top_city_per_state <- us_cities %>%
  filter(within_160_km) %>%
  group_by(state_name) %>%
  slice_max(population, n = 1, with_ties = FALSE) %>%
  ungroup()

ggplot() +
  geom_sf(data = st_union(states), fill = "grey85", color = "white") +
  geom_sf(data = us_cities, aes(color = as.numeric(within_160_km)), size = 0.5) +
  geom_sf(data = top_city_per_state, color = "black", size = 1) +
  ggrepel::geom_label_repel(
    data = top_city_per_state,
    aes(geometry = geometry, label = city),
    stat = "sf_coordinates",
    size = 3,
    color = "black",
    fill = "white"
  ) +
  scale_color_gradient(low = "orange", high = "darkred", guide = "none") +
  gghighlight(within_160_km) +
  theme_void() +
  labs(title = "Most Populous City per State in 160km Border Zone")
```

